### DISCUSSION TITLE
Error with basic example

### DISCUSSION THREAD

**Discussion by nmoagit** [maxcountryman/axum-login#176] [Q&A]
I copied the example code snippets to  get started and I get an unexpected error  for the line

```rust
    let app = Router::new()
        .route("/protected", get(todo!()))
        .route_layer(login_required!(Backend, login_url = "/login"))
        .route("/login", post(todo!()))
        .route("/login", get(todo!()))
        .layer(auth_layer);   <-- error here 
```
and the error is

```rust
the trait bound `Infallible: From<Box<(dyn std::error::Error + Send + Sync + 'static)>>` is not satisfied
```

I am complete lost

**Comment by maxcountryman** [comment]
Please note that the code snippets are by design incomplete. I'd recommend copying from the examples instead if you can.

That specific error is indicating your dependencies are likely not in sync. What does your Cargo.toml look like?

**Comment by nmoagit** [comment]
>  What does your Cargo.toml look like?

```toml
[dependencies]
axum          = "0.7.2"
chrono        = { version = "0.4.24", features = ["serde"] }
dotenv        = "0.15.0"
serde         = { version = "1.0.159", features = ["derive"] }
serde_json    = "1.0.95"
sqlx          = { version = "0.7.3", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
tokio         = { version = "1.27.0", features = ["full"] }
tower-http    = { version = "0.5.0", features = ["cors"] }
uuid          = { version = "1.3.0", features = ["serde", "v4"] }
tsync         = "1"
async-trait   = "0.1.74"
password-auth = "1.0.0"
axum-login    = "0.10.1"
```
